FROM ruby

RUN groupadd -r cucumber && useradd -r -g cucumber -G audio,video cucumber \
    && mkdir -p /home/cucumber && chown -R cucumber:cucumber /home/cucumber

USER cucumber

COPY Gemfile /home/cucumber/Gemfile

WORKDIR /home/cucumber
RUN gem install bundler && bundle install

CMD bundle exec cucumber --profile json_report
