require 'rubygems'
require 'bundler'
require 'rspec/core/rake_task'
#require 'cucumber'
#require 'cucumber/rake/task'

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.ruby_opts = "-I lib:spec"
  spec.pattern = 'spec/**/*_spec.rb'
end
task :spec

#Cucumber::Rake::Task.new(:features, "Run the cucumber features")


desc 'Run all specs and cukes'
#task :test => ['spec', 'features']
task :test => ['spec']

task :default => :test